[build-system]
requires = [
  "setuptools >= 75.5.0",
  "requests ~= 2.34.2",
]
build-backend = "setuptools.build_meta"

[project]
name = "sharly-chess-databases"
description = "Sharly Chess databases utilities"
requires-python = ">=3.13.0"
version = "1.0.0"

authors = [
  { name = "Pascal Aubry", email = "support@sharly-chess.com" },
  { name = "Sammy Plat", email = "support@sharly-chess.com" },
  { name = "Timothy Armes", email = "support@sharly-chess.com" },
  { name = "Youri Aubry", email = "support@sharly-chess.com" },
]

dependencies = [
  "chardet ~= 7.4.3",
  "cryptography ~= 49.0.0",
  "httpdate ~= 1.2.0",
  "requests ~= 2.34.2",
]

[project.optional-dependencies]
lint = [
  "ruff ~= 0.15.0",
  "validate-pyproject ~= 0.25",
  "pipdeptree ~= 4.1.0",
  "mypy >= 2.3.0",
  "pre-commit ~= 4.6.1",
]

ffe-france-pre-registration = [
  "pyodbc ~= 5.3.0",
]

[tool.ruff.format]
quote-style = "single"

[tool.mypy]
check_untyped_defs = true
disable_error_code = ["import-untyped", "no-redef"]
